### ISSUE TITLE
Datasets used to train this

### ISSUE THREAD

**Issue by elemets** [plpla/DeepCCS#11]
Hi

I'm doing my own research into creating a model to predict the CCS, are the datasets you used publicly available, and if so would you be able to show me where to find them?

Thank you
Arthur

**Comment by plpla** [comment]
Hi Arthur,
all the datasets used here are described in the [paper](https://pubs.acs.org/doi/abs/10.1021/acs.analchem.8b05821) and most if not all datasets are included in the DATASETS.h5 file in the repo.
Let me know if you can't find something or if you need more details!
