### ISSUE TITLE
Add default model adducts to the documentation

### ISSUE THREAD

**Issue by Danissss** [plpla/DeepCCS#6]

**Comment by plpla** [comment]
You are right, this should be mentionned in the documentation. We will fix this.
Here is the list: M-2H, M+Na, M-H and M+H
More adducts can be handled if you train your own model.

**Comment by plpla** [comment]
The information is already there: https://github.com/plpla/DeepCCS#additional-notes
We should make it easier to find...

**Comment by Danissss** [comment]
Sorry, my mistake.

**Comment by plpla** [comment]
@Danissss can you send us your e-mail adress at pier-luc.plante.1@ulaval.ca? If you are interested, we would like you to try the web interface for DeepCCS we are developping. Thanks!

**Comment by Danissss** [comment]
Sure, glad to help.
danis.cao@hotmail.com
