### ISSUE TITLE
Input file

### ISSUE THREAD

**Issue by magnuspalmblad** [plpla/DeepCCS#9]
What is the separator(s) expected in the input file? Space, comma or tab? Should there be a header line with "SMILES" and "Adducts" column headers? Perhaps a simple example input file or more detailed description in the README would be nice? Excited to take DeepCCS for a spin...

**Comment by plpla** [comment]
The input file is expected to be either a csv or xlsx file. The CSV separator should be a comma.
The file must at least contain the following columns: SMILES and Adducts.

We will add a demo file to make this easier in the future. Let us know if you have more issues!
